export const ProductDemo = [
    {
      title: "Tomato",
      rating: 4.7,
      ratingNumber: 120,
      brand: "Farm Fresh",
      img: "https://www.example.com/tomato.jpg",
      price: 1.99,
      offerPrice: 1.49,
    },
    {
      title: "Carrot",
      rating: 4.3,
      ratingNumber: 85,
      brand: "Organic Harvest",
      img: "https://www.example.com/carrot.jpg",
      price: 0.99,
      offerPrice: 0.79,
    },
    {
      title: "Broccoli",
      rating: 4.6,
      ratingNumber: 95,
      brand: "Green Fields",
      img: "https://www.example.com/broccoli.jpg",
      price: 2.49,
      offerPrice: 2.19,
    },
    {
      title: "Cucumber",
      rating: 4.2,
      ratingNumber: 78,
      brand: "Garden Fresh",
      img: "https://www.example.com/cucumber.jpg",
      price: 0.79,
      offerPrice: 0.59,
    },
    {
      title: "Spinach",
      rating: 4.5,
      ratingNumber: 92,
      brand: "Leafy Farms",
      img: "https://www.example.com/spinach.jpg",
      price: 1.29,
      offerPrice: 0.99,
    },
    {
      title: "Potato",
      rating: 4.4,
      ratingNumber: 110,
      brand: "Starchy Foods",
      img: "https://www.example.com/potato.jpg",
      price: 0.89,
      offerPrice: 0.69,
    },
    {
      title: "Bell Pepper",
      rating: 4.8,
      ratingNumber: 105,
      brand: "Colorful Veggies",
      img: "https://www.example.com/bellpepper.jpg",
      price: 1.79,
      offerPrice: 1.59,
    },
    {
      title: "Zucchini",
      rating: 4.2,
      ratingNumber: 70,
      brand: "Garden Delights",
      img: "https://www.example.com/zucchini.jpg",
      price: 1.49,
      offerPrice: 1.29,
    },
    {
      title: "Eggplant",
      rating: 4.1,
      ratingNumber: 68,
      brand: "Purple Produce",
      img: "https://www.example.com/eggplant.jpg",
      price: 1.69,
      offerPrice: 1.49,
    },
    {
      title: "Cabbage",
      rating: 4.3,
      ratingNumber: 75,
      brand: "Crisp Greens",
      img: "https://www.example.com/cabbage.jpg",
      price: 1.29,
      offerPrice: 0.99,
    },
  ];
  
  