export const ProductDemo = [
    {
      title: "Tomato",
      rating: 47,
      ratingNumber: 120,
      brand: "Farm Fresh",
      img: "https://wwwexamplecom/tomatojpg",
      price: 199,
      offerPrice: 149,
    },
    {
      title: "Carrot",
      rating: 43,
      ratingNumber: 85,
      brand: "Organic Harvest",
      img: "https://wwwexamplecom/carrotjpg",
      price:99,
      offerPrice:79,
    },
    {
      title: "Broccoli",
      rating: 46,
      ratingNumber: 95,
      brand: "Green Fields",
      img: "https://wwwexamplecom/broccolijpg",
      price: 249,
      offerPrice: 219,
    },
    {
      title: "Cucumber",
      rating: 42,
      ratingNumber: 78,
      brand: "Garden Fresh",
      img: "https://wwwexamplecom/cucumberjpg",
      price:79,
      offerPrice:59,
    },
    {
      title: "Spinach",
      rating: 45,
      ratingNumber: 92,
      brand: "Leafy Farms",
      img: "https://wwwexamplecom/spinachjpg",
      price: 129,
      offerPrice:99,
    },
    {
      title: "Potato",
      rating: 44,
      ratingNumber: 110,
      brand: "Starchy Foods",
      img: "https://wwwexamplecom/potatojpg",
      price: 89,
      offerPrice: 69,
    },
    {
      title: "Bell Pepper",
      rating: 48,
      ratingNumber: 105,
      brand: "Colorful Veggies",
      img: "https://wwwexamplecom/bellpepperjpg",
      price: 179,
      offerPrice: 159,
    },
    {
      title: "Zucchini",
      rating: 42,
      ratingNumber: 70,
      brand: "Garden Delights",
      img: "https://wwwexamplecom/zucchinijpg",
      price: 149,
      offerPrice: 129,
    },
    {
      title: "Eggplant",
      rating: 41,
      ratingNumber: 68,
      brand: "Purple Produce",
      img: "https://wwwexamplecom/eggplantjpg",
      price: 169,
      offerPrice: 149,
    },
    {
      title: "Cabbage",
      rating: 43,
      ratingNumber: 75,
      brand: "Crisp Greens",
      img: "https://wwwexamplecom/cabbagejpg",
      price: 129,
      offerPrice: 99,
    },
  ];
  
  